# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: uthaya1997/my-python-app:v12  # Replace with your Docker image name
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
