apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000  # Grafana default port
      targetPort: 3000
  type: LoadBalancer  # Expose externally via LoadBalancer
