apiVersion: v1                # API version for the Service object.
kind: Service                  # Specifies that this is a Service.
metadata:
  name: prometheus             # The name of the service.
spec:
  selector:
    app: prometheus            # The label selector to associate with the pods.
  ports:
    - protocol: TCP            # The protocol for the service (TCP in this case).
      port: 9090                # The port exposed by the service.
      targetPort: 9090          # The port on the pod where the service forwards traffic.
  type: LoadBalancer            # Exposes the service through a cloud provider's load balancer.
